version: "3.9"

services:
  kalkulator:
    image: mohamadfikriisfahani/kalkulator-app:latest
    container_name: kalkulator-app
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
